config/routes.rb
Rails.application.routes.draw do
  root to: "public/items#index"
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  delete "public/cart_items/destroy_all" => "public/cart_items#destroy_all", as: "destroy_all"
  namespace :public do
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update]
    resources :cart_items, only: [:index, :update, :create, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
  end
  get "public/customers/:id/confirm_with" => "public/customers#confirm_with", as: "confirm_with"
  patch "public/customers/:id/withdraw" => "public/customers#withdraw", as: "withdraw"
  post "public/orders/confirm" => "public/orders#confirm", as: "confirm"
  get "public/orders/complete" => "public/orders#complete", as: "complete"
  
# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :order
  belongs_to :customer
  
    # 小計
  def subtotal
    item.with_tax_price*amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_item
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :cart_item
    has_one_attached :image
    
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  
    # 単価
  def with_tax_price
    (price*1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :cart_item
  
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customer = Customer.page(params[:page])
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to public_customer_path(current_customer.id)
  end
  
  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :telephone_number, :address)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @item = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end


  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    admin_items_path
  end
  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :configure_permitted_parameters, if: :devise_controller?

  def search
    @publics = Public.search(params[:search])
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/customers/edit.html.erb
<h2>編集</h2>
<%= form_with model: @customer, url: public_customer_path(@customer.id) do |f| %>
  <label for = "inputName">名前</label>
  <%= f.text_field :first_name, autofocus: true, id:"inputName", placeholder:"名前" %>
  <%= f.submit "保存"%>
<% end %>

app/views/admin/customers/index.html.erb
<main>
  <h4>会員一覧</h4>
  <table class = "table">
    <thead>
      <tr>会員ID</tr>
      <tr>指名</tr>
      <tr>メールアドレス</tr>
      <tr>ステータス</tr>
    </thead>
    <% @customer.each do |customer| %>
      <tbody>
        <tr>
          <th><%= link_to"#{customer.id}", admin_customer_path(customer.id) %></th>
          <th><%= customer.last_name %><%= customer.first_name %></th>
          <th><%= customer.email %></th>
        </tr>
      </tbody>
    <% end %>
  </table>
  <%= paginate @customer %>
</main>

app/views/admin/customers/show.html.erb
<main>
  <h3><%= @customer.last_name %><%= @customer.first_name %>の会員詳細</h3>
  <h4>会員ID</h4>
  <%= @customer.id %>
  <h4>氏名</h4>
  <%= @customer.last_name %><%= @customer.first_name %>
  <h4>フリガナ</h4>
  <%= @customer.last_name_kana %><%= @customer.first_name_kana %>
  <h4>郵便番号</h4>
  <%= @customer.postal_code %>
  <h4>住所</h4>
  <%= @customer.address %>
  <h4>電話番号</h4>
  <%= @customer.telephone_number %>
  <h4>メールアドレス</h4>
  <%= @customer.email %>
  
  <%= link_to "編集する", edit_admin_customer_path(@customer.id) %>
</main>

app/views/admin/items/edit.html.erb
<main>
  <h4>商品詳細</h4>
  <%= form_with model: @item, url: admin_item_path(@item.id) do |f|%>
    <label for="inputName">商品名</label>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder: @item.name %>
    <label for="inputintroduction">商品紹介</label>
    <%= f.text_area :introduction, autofocus: true, id:"inputintroduction",  placeholder: @item.introduction %> 
    <label for="inputprice">価格</label>
    <%= f.text_field :price, autofocus: true, id:"inputprice", placeholder: @item.price %>
    <%= f.submit "変更を保存" %>
  <% end %>
</main>

app/views/admin/items/index.html.erb
<main>
  <div>
    <%= link_to "新規登録", new_admin_item_path %>  
  </div>
  <table class = "table">
    <thead>
      <tr>商品ID</tr>
      <tr>商品名</tr>
      <tr>商品価格</tr>
    </thead>
    <% @item.each do |item| %>
      <tbody>
        <tr>
          <th><%= item.id %></th>
          <th><%= item.name %></th>
          <th><%= item.price %></th>
        </tr>
      </tbody>
    <% end %>
  </table>
  <%= paginate @item %>
</main>

app/views/admin/items/new.html.erb
<main>
  <h3>商品新規登録</h3>
  <%= form_with model: @item, url: admin_items_path do |f| %>
    <h4>画像</h4>
    <%= f.file_field :image, accept: "image/*" %>
    <h4>商品名</h4>
    <%= f.text_field :name %>
    <h4>商品紹介</h4>
    <%= f.text_area :introduction %>
    <h4>価格</h4>
    <%= f.text_field :price %>
    <%= f.submit "新規登録" %>
  <% end %>
</main>

app/views/admin/items/show.html.erb
<main>
  <h4>商品詳細</h4>
   <%= image_tag item.get_image %>
   <h4>商品名</h4>
    <%= @item.name %>
    <h4>商品紹介</h4>
    <%= @item.introduction %>
    <h4>価格</h4>
    <%= @item.price %>
    <%= link_to "編集する", edit_admin_item_path(@item.id) %>
</main>